name: "Use External Composite Action"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout External Action Repository
        uses: actions/checkout@v4
        with:
          repository: ravishansenevirathna/my-composite-action
          ref: main
          path: my-composite-action

      - name: Use Composite Action from External Repo
        uses: ./my-composite-action/.github/actions/setup-environment@v1.0.0
        with:
          node-version: "18"